title: Taste Technologists
description: A web application with easy and delicious recipes for college students with limited resources. ![ci-badge](https://github.com/taste-technologists/taste-technologists/workflows/taste-technologists/badge.svg)
google_analytics:
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions